### ISSUE TITLE
Inference for downstream tasks

### ISSUE THREAD

**Issue by ac5113** [cvlab-columbia/pix2gestalt#18]
Hello,
Do you plan to provide inferencing for the downstream applications mentioned, such as 3D reconstruction from occluded RGB image?

**Comment by egeozguroglu** [comment]
Hi, thanks for the interest in our work! Since we synthesize RGB images of whole objects (i.e. perform amodal completion and segmentation), our approach makes it straightforward to equip various computer vision methods with the ability to handle occlusions, beyond amodal segmentation.

After performing amodal completion, for recognition, we use [CLIP](https://github.com/openai/CLIP) as the base open-vocabulary classifier. For novel view synthesis and 3D reconstruction, we use [SyncDreamer](https://github.com/liuyuan-pal/SyncDreamer). Since these codebases are very clean & well-documented, we don't plan to provide the intermediary code here. Moreover, please note that our approach is not specific to any particular recognition, or NVS/3D reconstruction model. Instead, it serves as a drop-in module to enable them to handle occlusions. 

That said, please feel free to contact me at ege.ozguroglu@columbia.edu for specific scripts.

**Comment by ac5113** [comment]
Thanks for the response!
I'll be sure to do so
