### ISSUE TITLE
Testing script for amodal segmentation on COCOA

### ISSUE THREAD

**Issue by trqminh** [cvlab-columbia/pix2gestalt#6]
Thank you for the interesting work!
I would like to ask if you have the script to generate the result in Table 1 in the paper for amodal segmentation results.

**Comment by egeozguroglu** [comment]
Hi, we based our Amodal COCO and Amodal BSDS evaluation for amodal segmentation (Table 1) on the [Amodal COCO API source code](https://github.com/Wakeupbuddy/amodalAPI), using the inference functionality provided [here](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/inference.py). 

Specifically, we sample multiple predictions from the diffusion process. Since our method is probabilistic, it encodes the inherent ambiguity and under-constrained nature of amodal completion.

For each predicted whole (amodal completion), we retrieve the corresponding binary amodal masks, then compute the best of 3 with majority voting — as reported in our paper. 

Does this make sense? Please feel free to email me at [ege.ozguroglu@columbia.edu](mailto:ege.ozguroglu@columbia.edu) for any further details!

**Comment by trqminh** [comment]
Hi @egeozguroglu , thanks for your response.
It makes sense to me, I know how the procedure looks like. My question is whether you have the script of this procedure, meaning that I can run it and get the number that you reported in the paper.
